name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node + pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      # 3. Install Capacitor & project deps
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D @capacitor/cli
          pnpm add @capacitor/core
          pnpm add @capacitor/android@latest

      # 4. Add Android platform
      - name: Add Android platform
        run: pnpm exec cap add android || echo "Android already added"

      # 5. Setup JDK & Android SDK
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 6. Build APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 7. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
