name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # Configure PNPM global bin directory
      - name: Setup PNPM global bin
        run: |
          echo "PNPM_HOME=$HOME/.pnpm" >> $GITHUB_ENV
          echo "$HOME/.pnpm" >> $GITHUB_PATH
          mkdir -p $HOME/.pnpm

      # Install TypeScript globally
      - name: Install TypeScript globally
        run: pnpm add -g typescript

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install

      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Build APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk


