# .github/workflows/build-android.yml

name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm run build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add Android Platform
        run: pnpm exec cap add android

      - name: Sync Capacitor project
        run: pnpm exec cap sync android

      # THIS IS THE NEW STEP THAT FIXES THE JAVA ERROR
      - name: Patch Gradle Configuration
        run: |
          cd android
          sed -i "s/androidxAppCompatVersion = '.*'/androidxAppCompatVersion = '1.6.1'/" variables.gradle
          cd ..

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Translator.app-release-signed.apk
          path: android/app/build/outputs/apk/release/app-release-signed.apk
