name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'


      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install dependencies
        run: npx pnpm install

      - name: Build web app
        run: npx pnpm run build

      # Use Java 17 for better Android compatibility
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Add Android Platform
        run: npx pnpm exec cap add android

      - name: Sync Capacitor project
        run: npx pnpm exec cap sync android

      # Fix keystore path for standard Capacitor structure
      - name: Decode Keystore
        working-directory: android
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

      - name: Build and Sign Release APK
        working-directory: android
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=app/release.keystore \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
